[package]
name = "wattou-bot"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bot"

# [[bin]]
# name = "wattiez-parser"

[dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15"
poise = "0.7.0"
time = { version = "0.3.48", features = ["parsing", "macros", "local-offset"] }
ics = "0.5.8"
uuid = { version = "1.23.3", features = ["v5"] }
once_cell = "1.21.4"
thiserror = "2.0.18"
bitflags = { version = "2.13.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
ron = "0.12.2"
color-eyre = "0.6.5"
